spring:
  datasource:
    url: jdbc:mysql://localhost:3306/snapthetitle?useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: root
    password: wjswnsgur0218!
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

  flyway:                         # ← 여기가 반드시 spring: 의 하위여야 합니다
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true     # ← 이 옵션이 있어야 기존 스키마를 baseline 처리합니다

server:
  port: 8080

  # src/main/resources/application.yml

logging:
  level:
    org.springframework.security: DEBUG
