-- V2__alter_deleted_yn.sql
ALTER TABLE ATTACHMENTS     MODIFY COLUMN DELETED_YN VARCHAR(1) NOT NULL DEFAULT 'N';
ALTER TABLE PRODUCTS        MODIFY COLUMN DELETED_YN VARCHAR(1) NOT NULL DEFAULT 'N';
ALTER TABLE PRODUCT_OPTIONS MODIFY COLUMN DELETED_YN VARCHAR(1) NOT NULL DEFAULT 'N';
ALTER TABLE FAQS            MODIFY COLUMN DELETED_YN VARCHAR(1) NOT NULL DEFAULT 'N';
ALTER TABLE PARTNERS        MODIFY COLUMN DELETED_YN VARCHAR(1) NOT NULL DEFAULT 'N';
ALTER TABLE GUIDES          MODIFY COLUMN DELETED_YN VARCHAR(1) NOT NULL DEFAULT 'N';
ALTER TABLE GUIDE_DETAILS   MODIFY COLUMN DELETED_YN VARCHAR(1) NOT NULL DEFAULT 'N';
